name: Add New Resource
description: Suggest a new resource to be added to the Awesome Mistral list
title: "[ADD] "
labels: ["enhancement", "new-resource"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to Awesome Mistral! Please fill out the form below.

  - type: input
    id: resource-name
    attributes:
      label: Resource Name
      description: Name of the project or resource
      placeholder: "e.g., MyMistralTool"
    validations:
      required: true

  - type: input
    id: resource-url
    attributes:
      label: Resource URL
      description: Link to the project (GitHub, website, etc.)
      placeholder: "https://github.com/..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which section should this resource be added to?
      options:
        - Official Mistral Resources
        - Models
        - Community Fine-Tuned Models
        - SDKs & APIs
        - Inference & Deployment
        - Fine-Tuning & Training
        - Model Merging & Quantization
        - Agents & Orchestration
        - Tooling & Dev Experience
        - Community Projects
        - Demos & Examples
        - Tutorials & Guides
        - Benchmarks & Evaluation
        - Research & Papers
        - Talks & Media
        - Ecosystem & Community
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Resource Type
      description: Is this an official Mistral project or a community project?
      options:
        - 🧠 Official Mistral
        - 🌍 Community
        - 🧪 Experimental
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief, technical description (one sentence)
      placeholder: "A tool for..."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why should this be added?
      description: Explain why this resource is high-quality and useful
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: The resource is actively maintained
          required: true
        - label: The link is working and accessible
          required: true
        - label: This resource is not already in the list
          required: true
        - label: The resource works with Mistral models
          required: true
