name: Report Dead Link
description: Report a broken or outdated link
title: "[DEAD LINK] "
labels: ["bug", "dead-link"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us maintain the quality of this list!

  - type: input
    id: dead-link
    attributes:
      label: Dead Link URL
      description: The URL that is no longer working
      placeholder: "https://..."
    validations:
      required: true

  - type: input
    id: resource-name
    attributes:
      label: Resource Name
      description: Name of the resource in the list
      placeholder: "e.g., SomeProject"
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      options:
        - 404 Not Found
        - Repository archived/deleted
        - Domain expired
        - Redirect to unrelated page
        - Other
    validations:
      required: true

  - type: input
    id: replacement
    attributes:
      label: Replacement URL (if known)
      description: If you know of an updated URL or alternative
      placeholder: "https://..."

  - type: dropdown
    id: recommendation
    attributes:
      label: Recommendation
      options:
        - Update the link
        - Remove from the list
        - Replace with alternative
    validations:
      required: true
